### ISSUE TITLE
Team28 DesignDoc Review: MIS Section 7

### ISSUE THREAD

**Issue by JasonSurendran** [dimitritsampiras/olympian#142]
Please retake a look at section 7 regarding the Fitness Unit of Measurement Type Module. You seem to have left the uses and semantics part of this section blank? If so then how would the module even be relevant in your program. Surely it would be accessed by other components of your code? Try to think about what other parts of your program would utilize the module in some capacity and add it in. It helps keep track of the interconnected parts of your overall capstone.

**Comment by Wililee** [comment]
The uses section is what this module uses not what uses this module
