### ISSUE TITLE
Team29 Review: Usability Survey Questions

### ISSUE THREAD

**Issue by Kabishan** [dimitritsampiras/olympian#85]
@CSchank

Solid effort on writing this Verification and Validation Plan. To validate several of the test cases for the non-functional requirements, such as, the "look and feel" and "text sizing and visibility" of the application, it was mentioned that user feedback would be used. Yet, there seems to be a lack of questions in Section 7.2: Usability Survey Questions to extract this feedback.

Also, a small formatting problem not worth a new issue. I think the traceability matrices are not necessarily placed one after the other.

**Comment by BasselR** [comment]
Thanks, implemented!
