### ISSUE TITLE
Review-VnV-Team29:Automated Testing and Verification Tools

### ISSUE THREAD

**Issue by albertzevanescent** [dimitritsampiras/olympian#86]
@CSchank

Section 3.6 Automated Testing and Verification Tools refers to section 3.5 of the problem statement instead of 3.6. The problem statement states TestCafe will be used for integration testing of various components, but there is no mention of it nor any integration tests in the VnV. Conversely, Apache JMeter is used for tests in the VnV but is not mentioned in the problem statement.

**Comment by BasselR** [comment]
Thanks, done!
