### ISSUE TITLE
Team29 Review:  Legal requirement and Usability survey questions

### ISSUE THREAD

**Issue by GaryGong27** [dimitritsampiras/olympian#87]
@CSchank

Well done on generating the VnV plan!

A couple thing could be improved, in section 4.2.8 legal requirements for testing the data protection, it would be better to reference the relevant data protection act in the appendix. Also, some of the NFR tests requires feedback from the users, so it is probably ideal to include some survey questions in the 7.2 to show the process of getting feedbacks.

**Comment by BasselR** [comment]
We've added an appendix link to the relevant data protection act, as well as listed our survey questions / procedure and how we will be incorporating the feedback.
Thanks for your feedback!
