### ISSUE TITLE
Review-VnV-Team29: Symbols, Abbr, & Acronyms, Symbolic Parameters, and Test Type

### ISSUE THREAD

**Issue by almen-ng** [dimitritsampiras/olympian#88]
The TA for this capstone group is: @CSchank 

Overall, great job on the VnV! 

With the VnV, I noticed that the Symbols, Abbreviations, & Acronyms table was removed from the VnV template. I believe it would be beneficial to have that in your VnV as there are some like `NFR`, `R`, and `iOS` that can put on there. 

As well, the Symbolic Parameters section in the Appendix has been left empty. If there are any constants that are included in your  documentation, such as `24 hours`, you can create and add the constant in that section.

Lastly, some tests are not identified properly as there are some tests that only have 1 type. Some tests can have more than 1 classification such as Functional and Manual. You can use these slides from 2AA4 (L29-34) as a reference - [2AA4 Slides](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/tree/master/Lectures)

**Comment by almen-ng** [comment]
Also, please create a label for our group and add it to the issues that we submit. Thanks!

**Comment by BasselR** [comment]
We've added the Symbols, Abbreviations, & Acronyms table back in, added relevant terminology, removed the irrelevant "Symbolic Parameters section", and specified test classifications. 
Thanks for your feedback!
