### ISSUE TITLE
Review-VnV-Team29: Software Validation Plan and Typos

### ISSUE THREAD

**Issue by JAYapeter** [dimitritsampiras/olympian#90]
Great work on the VnV plan! 

Regarding the Software Validation Plan, I think a bit more detail can be specified about what the meetings with each stakeholder will entail in terms of what type of feedback you are looking for from them and how the workflow of how you will change your current documentation and product.

A couple nitpicky items:
Under section 3.6 automated testing plan, is it supposed to refer to section 3.5 or 3.6 in the Problem Statement and Goals?

Under the test case derivation for test-FG-2, I believe there is a typo where "to" should be "the"

@CSchank

**Comment by BasselR** [comment]
Thanks, we've used your feedback to update Olympian's documentation!
